#ifndef MDUILIB_FRAMEWORK_CORE_RESOURCES_RESOURCESMANAGER_H
#define MDUILIB_FRAMEWORK_CORE_RESOURCES_RESOURCESMANAGER_H

namespace MDUILib
{
	class IResourcesManager
	{
		//TODO:
	};
}

#endif // !MDUILIB_FRAMEWORK_CORE_RESOURCES_RESOURCESMANAGER_H
