#ifndef MDUILIB_FRAMEWORK_COMMON_CORE_GRAPHICS_MFONT_H
#define MDUILIB_FRAMEWORK_COMMON_CORE_GRAPHICS_MFONT_H

namespace MDUILib
{
	struct MFont
	{
		//TODO:字体库考虑使用第三方库。
	};
}

#endif // !MDUILIB_FRAMEWORK_COMMON_CORE_GRAPHICS_MFONT_H
